name: Compile Radium ecosystem and generate artifacts

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [code-update-event]

jobs:     
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
     - name: Compute Radium Release
       id: releasename
       run: echo "::set-output name=RELEASE_NAME::Radium-$(date +'%Y-%m-%d')"
       
     - uses: seanmiddleditch/gha-setup-ninja@master
         
     - name: Add msbuild to PATH
       uses: microsoft/setup-msbuild@v1.0.0
       if: runner.os == 'Windows'
       with:
         vs-version: 16.6

     - name: Cache Qt
       id: cache-qt
       uses: actions/cache@v1
       with:
         path: ../Qt
         key: ${{ runner.os }}-QtCache

     - name: Install Qt
       uses: jurplel/install-qt-action@v2
       with:
         cached: ${{ steps.cache-qt.outputs.cache-hit }}
         
     - shell: bash
       name: Clone Radium
       run: |
         echo "Release name: ${{steps.releasename.outputs.RELEASE_NAME}}-${{ runner.os }}"
         mkdir -p install/
         mkdir -p src && cd src && git clone https://github.com/STORM-IRIT/Radium-Engine.git --single-branch && cd ..
         mkdir -p build/Radium-Engine
         
     - shell: bash
       name: Configure Radium For Windows
       if: runner.os == 'Windows'
       run: |
         cd build/Radium-Engine 
         cmake ../../src/Radium-Engine -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../install/ -DRADIUM_IO_ASSIMP=FALSE -DCMAKE_EXECUTE_PROCESS_COMMAND_ECHO=STDOUT -DRADIUM_UPDATE_VERSION=OFF -DRADIUM_EXTERNAL_CMAKE_INSTALL_MESSAGE=LAZY
         
     - shell: bash
       name: Configure Radium For Macos and Linux
       if: runner.os != 'Windows'
       run: |
         cd build/Radium-Engine 
         cmake ../../src/Radium-Engine -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../install/ -DRADIUM_IO_ASSIMP=TRUE -DCMAKE_EXECUTE_PROCESS_COMMAND_ECHO=STDOUT -DRADIUM_UPDATE_VERSION=OFF -DRADIUM_EXTERNAL_CMAKE_INSTALL_MESSAGE=LAZY
         
     - shell: bash
       name: Build Radium
       run: |
         cd build/Radium-Engine 
         cmake --build . --parallel --config Release --target install
         
     - shell: bash
       name: Clone and configure Radium Apps
       run: |
         cd src 
         git clone https://github.com/STORM-IRIT/Radium-Apps.git --branch master --single-branch
         cd ..
         mkdir -p build/Radium-Apps
         cd build/Radium-Apps 
         cmake ../../src/Radium-Apps -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../install/ -GNinja -DRadium_DIR=../../install/lib/cmake/Radium
         cmake --build . --parallel --config Release --target install
     
     - shell: bash  
       name: Generate zip files
       run: |
         mv install ${{steps.releasename.outputs.RELEASE_NAME}}-${{ runner.os }}
         zip -r ${{steps.releasename.outputs.RELEASE_NAME}}-${{ runner.os }}.zip ${{steps.releasename.outputs.RELEASE_NAME}}-${{ runner.os }}

     - name: Upload artifact
       uses: actions/upload-artifact@v1
       with:
         name: binaries
         path: ${{steps.releasename.outputs.RELEASE_NAME}}-${{ runner.os }}.zip
       
  create_release:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      
     - shell: bash
       name: Compute Radium Release
       id: releasename
       run: echo "::set-output name=RELEASE_NAME::Radium-$(date +'%Y-%m-%d')"
       
     - name: Create Release
       id: create_release
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: ${{ github.ref }}
         release_name: ${{steps.releasename.outputs.RELEASE_NAME}}
         draft: true
         prerelease: true

     - shell: bash
       run: echo ${{ steps.create_release.outputs.upload_url }} >> release-url.txt

     - name: Save upload url for next stop
       uses: actions/upload-artifact@v1
       with:
         name: releaseurl
         path: release-url.txt


  upload_release:
    needs: [create_release]
    runs-on: ${{ matrix.os }}
    if: always()
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:   
         
     - name: Load artifacts from build
       uses: actions/download-artifact@v1
       with:
          name: releaseurl
      
     - shell: bash
       name: Compute Radium Release
       id: releaseinfo
       run: |
        echo "::set-output name=RELEASE_URL::`cat releaseurl/release-url.txt`"
        echo "::set-output name=RELEASE_NAME::Radium-$(date +'%Y-%m-%d')"
         
     - name: Load artifacts from build
       uses: actions/download-artifact@v1
       with:
          name: binaries
         
     - name: Upload Release Asset
       id: upload-release-asset
       uses: actions/upload-release-asset@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{steps.releaseinfo.outputs.RELEASE_URL}}
         asset_path: ./binaries/${{steps.releaseinfo.outputs.RELEASE_NAME}}-${{ runner.os }}.zip
         asset_name: ${{steps.releaseinfo.outputs.RELEASE_NAME}}-${{ runner.os }}.zip
         asset_content_type: application/zip

